config/routes.rb
FaceRecognition::Application.routes.draw do
  resources :clients
  root :to => 'clients#new'
  match "/clientes", to: 'clients#index', via: :all

  

end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :email, :presence => { :message => "=> You must insert a valid email. " }, :format => {:with => /@/}
	validates :image, :presence => { :message => "=> You must insert a valid image. "}, :format => {:with => /(?:jpg|gif|png|jpeg)/}
	validates :nombre, :presence => { :message => "=> You must insert your name. "}, :length => {:minimum => 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    data = Unirest::get("https://lambda-face-detection-and-recognition.p.mashape.com/detect?images="+@client.image, 
          {
            "X-Mashape-Authorization" => "9Ljq88hL9yiUHoVngDpaqgAFblpGPEHZ"
          }
     ).body.to_json
    data = JSON.parse(data)
    @images = data["photos"]
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:nombre, :email, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="col-sm-12 col-md-6 col-lg-6 well">
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-user"></span>
      <%= f.text_field :nombre, :class => "form-control", :placeholder=>"Name" %>  
    </div>
  </div>
  <div class="form-group">
      <div class="input-group">
        <span class="input-group-addon glyphicon glyphicon-envelope"></span>
        <%= f.text_field :email, :class => "form-control", :placeholder=>"Email" %>  
      </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-link"></span>
      <%= f.text_field :image, :class => "form-control", :placeholder=>"Image" %>  
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Send", :class=>"btn btn-success" %>
    <a href="#" id="reset" class="btn btn-danger">Cancel</a>
  </div>
<% end %>

</div>

app/views/clients/destroy.js.erb
$("#<%= dom_id(@client) %>").fadeOut();

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing Faces</h1>
<div class="row">
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 well">
    <a href="#" class="btn btn-info btn-large" id="action_table">Show Table</a>    
    <table class="table table-bordered table-hover" style="display:none">
      <thead>
        <tr>
          <th><span class="glyphicon glyphicon-user"></span> Nombre</th>
          <th><span class="glyphicon glyphicon-envelope"></span> Email</th>
          <th><span class="glyphicon glyphicon-picture"></span> Image</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.nombre %></td>
            <td><%= client.email %></td>
            <td><a href="<%= client.image %>" title="Image"><%= client.image %></a></td>
            <td><%= link_to 'Show', client %></td>
            <td><%= link_to 'Edit', edit_client_path(client) %></td>
            <td><%= link_to 'Destroy', client, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
<% @clients.each do |client| %>

  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= client.image %>" alt="...">
      <div class="caption">
        <h3><%= client.nombre %></h3>
        <p class="well"><%= link_to "View", client, :class=>"btn btn-success" %><%= link_to "Edit", edit_client_path(client), :class => "btn btn-info" %><%= link_to "Delete", client, method: :delete, remote: true, :class=>"btn btn-danger", data: {confirm: "You really want to delete this?"} %></p>
      </div>
    </div>
  </div>

<% end %>
</div>
<br>
<%= link_to 'New Client', new_client_path, :class => "btn btn-info" %>

app/views/clients/new.html.erb
<div class="row">
    <div class="col-md-12 well facerecognition_flyer">
      	<h1><button class="btn btn-success btn-lg"><img src="http://simpleicon.com/wp-content/uploads/smile.png" width="50" height="50" alt="Smiling :)"/></button>  FaceRecognition</h1>
        <p class="lead">This is a rails web app that consumes the <a href="https://www.mashape.com/lambda/face#!documentation">Face</a> API. It detects your <b>face</b>, <b>eyes</b>, <b>mouth</b>, <b>nose</b>, <b>smile rate</b> and your <b>confidence rate</b>.</p>
  	</div>        
</div>

<h1>Test Your Face</h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<%

@images.each do |image|  
	image["tags"].each do |features|

%>


  <style>
  	.Face{
  		width: <%= image["width"] %>;
  		height: <%= image["height"] %>;
  		position: absolute;
  		z-index: 1;
  	}
  	.FaceRecognition{
  		width: <%= image["width"] %>;
  		height: <%= image["height"] %>;
  	}
  	.ojoizquierdo, .ojoderecho, .nariz{
  		border-style:solid;
		border-width:1px;
		border-color: red;
		border-radius: 100%;
		-moz-border-radius: 100%;
		-webkit-border-radius: 100%;
		-ms-border-radius: 100%;
		-o-border-radius: 100%;
  		position: absolute;
  		z-index: 999;
  		width: 10px;
  		height: 10px;
  	}
  	.ojoizquierdo{
  		margin-left: <%= features["eye_left"]["x"]-5 %>px;
  		margin-top: <%= features["eye_left"]["y"] %>px;
  		border-color: white;
  	}
  	.ojoderecho{
  		margin-left: <%= features["eye_right"]["x"]-5 %>px;
  		margin-top: <%= features["eye_right"]["y"] %>px;
  	}
  	.nariz{
  		border-color: yellow;
  		margin-left: <%= features["nose"]["x"]+5 %>px;
  		margin-top: <%= features["nose"]["y"]-10 %>px;
  	}
  	.bocaizq, .bocader, .bocacent{
  		border-color: white;
  		background-color: black;
  		width: 10px;
  		height: 2px;
  		position: absolute;
  		z-index: 999;
  	}
  	.bocaizq{
  		margin-left: <%= features["mouth_left"]["x"] %>px;
  		margin-top: <%= features["mouth_left"]["y"] %>px;
  	}
  	.bocader{
  		margin-left: <%= features["mouth_right"]["x"] %>px;
  		margin-top: <%= features["mouth_right"]["y"] %>px;
  	}
  	.bocacent{
  		margin-left: <%= features["mouth_center"]["x"] %>px;
  		margin-top: <%= features["mouth_center"]["y"] %>px;
  	}
  </style>

<p id="notice"><%= notice %></p>

<p>
	<% attributes = features["attributes"].first %>

	<div class="row well" style="min-height:<%= image["height"]+70 %>px">
		<div class="col-md-6 col-sm-12 col-lg-6">
			<h1>FaceRecognition Results</h1>
			<h2><span class="glyphicon glyphicon-user"></span> 
				<%= @client.nombre %>
				<% if(attributes["smiling"]) %>
				<button class="btn btn-success"><img src="http://simpleicon.com/wp-content/uploads/smile.png" width="50" height="50" alt="Smiling :)"/></button>
				<% else %>
				<button class="btn btn-danger"><img src="http://simpleicon.com/wp-content/uploads/sad.png" width="50" height="50" alt="Sad :("/></button>
				<% end %>
			</h2>
			<div class="row">
				<table class="table table-hover table-bordered">
					<thead>
						<th>Attribute</th>
						<th>Rating</th>
					</thead>	
					<tbody>
						<tr>
							<td>Smile</td>
							<td><%= attributes["smile_rating"] * 100 %>%</td>
						</tr>
						<tr>
							<td>Confidence</td>
							<td><%= attributes["confidence"] * 100 %>%</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 col-lg-6">
		  <div class="FaceRecognition">
		  	<div class="ojoizquierdo" rel="tooltip" title="This is left eye"></div>
		  	<div class="ojoderecho" rel="tooltip" title="This is right eye"></div>
		  	<div class="nariz" rel="tooltip" title="This is nose"></div>
		  	<div id="boca" rel="tooltip" title="This is mouth">
		  		<div class="bocaizq"></div>
			  	<div class="bocacent"></div>
			  	<div class="bocader"></div>
		  	</div>
		  	<img class="Face thumbnail" src="<%= @client.image %>" width="<%= image["width"] %>" height="<%= image["height"] %>">
		  	<div class="caption">
		        <h2><%= @client.nombre %></h2>
		        <p>...</p>
		        <p><%= link_to "View", @client, :class=>"btn btn-primary" %></p>
		      </div>
		  </div>
		</div>
	</div>
  
  
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

<%	
	end
end
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceRecognition</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link href="http://bootswatch.com/slate/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:700' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag "application" %>
	<%= csrf_meta_tags %>

    <style>
    	body{
			padding-top: 70px;
    		font-family: 'Roboto', sans-serif;
    	}
	    h1, h2, h3{
	    	font-family: 'Roboto Condensed', sans-serif;
	    }
	    h4, h5{
	    	font-family: 'Roboto Condensed', sans-serif;
	    }
	    form p{
	    	font-family: 'Roboto Condensed', sans-serif;
	    }
	    .facerecognition_flyer{
	    	text-align: center;
	    }
    </style>
    <!--[if lt IE 9]>
      <script src="bootstrap/assets/js/html5shiv.js"></script>
      <script src="bootstrap/assets/js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="bootstrap/assets/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "FaceRecognition", root_path, :class=>"navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Clients", clients_path %></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <div class="row">
      	<div class="col-lg-12 col-md-12">
      		<%= yield %>
      	</div>
      </div>
      <hr>

      <footer>
        <p>&copy; <a href="http://briandiaz.me" title="Brian Diaz">BrianDiaz.me</a> 2013</p>
      </footer>
    </div><!-- /.container -->
	<script src="http://getbootstrap.com/assets/js/jquery.js"></script>
	<script src="http://getbootstrap.com/dist/js/bootstrap.js"></script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  </body>
</html>